### ISSUE TITLE
Error serialization does not preserve extra properties

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#91]
With this code:

```ts
import superjson from "superjson";

const error = new Error("Prisma error");
error.code = "P2002";
error.meta = {
  target: ["email"]
};

console.log(superjson.serialize(error));
```

You get this log. **The `error.code` and `error.meta` items are missing.**

```
{json: Object, meta: Object}
json: Object
name: "Error"
message: "Prisma error"
stack: "Error: Prisma error
    at evaluate (https://168ls.csb.app/src/index.js:10:13)
    at z (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:98988)
    at X.evaluate (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:111112)
    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:120692)
    at c (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:110858)
    at loadResources (https://168ls.csb.app/index.html:3:2)
    at evaluate (https://168ls.csb.app/index.html:9:3)
    at z (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:98988)
    at X.evaluate (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:111112)
    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:120692)
    at ye.evaluateModule (https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:120428)
    at https://codesandbox.io/static/js/sandbox.bd8b2d7a3.js:1:811018
    at l (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257407)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257160)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257764)
    at t (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2616)"
meta: Object
values: Array(1)
0: "Error"
```

[Codesandbox reproduction](https://codesandbox.io/s/zealous-davinci-168ls?file=/src/index.js)

**Comment by Skn0tt** [comment]
Correct. This is because these non-standard properties are potentially dangerous to expose (think about an error that includes some database connection details).

@KATT mentioned that even `stack` could be dangerous to expose: https://github.com/blitz-js/superjson/issues/85#issue-774721935

We could add an optional flag like `SuperJSON.allowErrorProps("meta", "code")`. Would that fix your problem?

**Comment by flybayer** [comment]
Ah, ok.

> We could add an optional flag like `SuperJSON.allowErrorProps("meta", "code")`. Would that fix your problem?

Yes I think this would be very good for Prisma errors.
